// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate miqt-uic -Qt6 -InFile ui/popup.ui -OutFile popup.go

package main

import (
	qt "github.com/mappu/miqt/qt6"
)

type DialogUi struct {
	Dialog         *qt.QDialog
	verticalLayout *qt.QVBoxLayout
	formLayout     *qt.QFormLayout
	urlInput       *qt.QLineEdit
	urlLabel       *qt.QLabel
	nameLabel      *qt.QLabel
	nameInput      *qt.QLineEdit
	buttonBox      *qt.QDialogButtonBox
}

// NewDialogUi creates all Qt widget classes for Dialog.
func NewDialogUi() *DialogUi {
	ui := &DialogUi{}
	ui.Dialog = qt.NewQDialog(nil)
	Dialog__objectName := qt.NewQAnyStringView3("Dialog")
	ui.Dialog.SetObjectName(*Dialog__objectName)
	Dialog__objectName.Delete() // setter copied value
	ui.Dialog.Resize(400, 160)
	ui.verticalLayout = qt.NewQVBoxLayout(ui.Dialog.QWidget)
	verticalLayout__objectName := qt.NewQAnyStringView3("verticalLayout")
	ui.verticalLayout.SetObjectName(*verticalLayout__objectName)
	verticalLayout__objectName.Delete() // setter copied value
	ui.verticalLayout.SetContentsMargins(11, 11, 11, 11)
	ui.verticalLayout.SetSpacing(6)
	ui.formLayout = qt.NewQFormLayout2()
	formLayout__objectName := qt.NewQAnyStringView3("formLayout")
	ui.formLayout.SetObjectName(*formLayout__objectName)
	formLayout__objectName.Delete() // setter copied value
	ui.formLayout.SetLabelAlignment(qt.AlignRight | qt.AlignTrailing | qt.AlignVCenter)
	ui.formLayout.SetFormAlignment(qt.AlignLeading | qt.AlignLeft | qt.AlignVCenter)
	ui.formLayout.SetContentsMargins(11, 11, 11, 11)
	ui.formLayout.SetSpacing(6)
	ui.urlInput = qt.NewQLineEdit(ui.Dialog.QWidget)
	urlInput__objectName := qt.NewQAnyStringView3("urlInput")
	ui.urlInput.SetObjectName(*urlInput__objectName)
	urlInput__objectName.Delete() // setter copied value

	ui.formLayout.SetWidget(1, qt.QFormLayout__FieldRole, ui.urlInput.QWidget)
	ui.urlLabel = qt.NewQLabel(ui.Dialog.QWidget)
	urlLabel__objectName := qt.NewQAnyStringView3("urlLabel")
	ui.urlLabel.SetObjectName(*urlLabel__objectName)
	urlLabel__objectName.Delete() // setter copied value

	ui.formLayout.SetWidget(1, qt.QFormLayout__LabelRole, ui.urlLabel.QWidget)
	ui.nameLabel = qt.NewQLabel(ui.Dialog.QWidget)
	nameLabel__objectName := qt.NewQAnyStringView3("nameLabel")
	ui.nameLabel.SetObjectName(*nameLabel__objectName)
	nameLabel__objectName.Delete() // setter copied value

	ui.formLayout.SetWidget(0, qt.QFormLayout__LabelRole, ui.nameLabel.QWidget)
	ui.nameInput = qt.NewQLineEdit(ui.Dialog.QWidget)
	nameInput__objectName := qt.NewQAnyStringView3("nameInput")
	ui.nameInput.SetObjectName(*nameInput__objectName)
	nameInput__objectName.Delete() // setter copied value

	ui.formLayout.SetWidget(0, qt.QFormLayout__FieldRole, ui.nameInput.QWidget)

	ui.verticalLayout.AddLayout(ui.formLayout.QLayout)
	ui.buttonBox = qt.NewQDialogButtonBox(ui.Dialog.QWidget)
	buttonBox__objectName := qt.NewQAnyStringView3("buttonBox")
	ui.buttonBox.SetObjectName(*buttonBox__objectName)
	buttonBox__objectName.Delete() // setter copied value
	ui.buttonBox.SetOrientation(qt.Horizontal)
	ui.buttonBox.SetStandardButtons(qt.QDialogButtonBox__Cancel | qt.QDialogButtonBox__Ok)

	ui.verticalLayout.AddWidget(ui.buttonBox.QWidget)

	ui.buttonBox.OnAccepted(ui.Dialog.Accept)
	ui.buttonBox.OnRejected(ui.Dialog.Reject)

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *DialogUi) Retranslate() {
	ui.Dialog.SetWindowTitle(qt.QCoreApplication_Tr("Add a Radio"))
	ui.urlLabel.SetText(qt.QDialog_Tr("URL"))
	ui.nameLabel.SetText(qt.QDialog_Tr("Name"))
}
