// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate miqt-uic -Qt6 -InFile ui/qmRadio.ui -OutFile ui.go

package main

import (
	qt "github.com/mappu/miqt/qt6"
)

type MainWindowUi struct {
	MainWindow     *qt.QMainWindow
	centralwidget  *qt.QWidget
	verticalLayout *qt.QVBoxLayout
	playerLayout   *qt.QHBoxLayout
	pauseButton    *qt.QPushButton
	stopButton     *qt.QPushButton
	previousButton *qt.QPushButton
	nextButton     *qt.QPushButton
	playerSlider   *qt.QSlider
	RadioList      *qt.QTableView
	menubar        *qt.QMenuBar
	statusbar      *qt.QStatusBar
}

// NewMainWindowUi creates all Qt widget classes for MainWindow.
func NewMainWindowUi() *MainWindowUi {
	ui := &MainWindowUi{}
	ui.MainWindow = qt.NewQMainWindow(nil)
	MainWindow__objectName := qt.NewQAnyStringView3("MainWindow")
	ui.MainWindow.SetObjectName(*MainWindow__objectName)
	MainWindow__objectName.Delete() // setter copied value
	ui.MainWindow.Resize(815, 578)
	ui.centralwidget = qt.NewQWidget(ui.MainWindow.QWidget)
	centralwidget__objectName := qt.NewQAnyStringView3("centralwidget")
	ui.centralwidget.SetObjectName(*centralwidget__objectName)
	centralwidget__objectName.Delete() // setter copied value
	ui.verticalLayout = qt.NewQVBoxLayout(ui.centralwidget)
	verticalLayout__objectName := qt.NewQAnyStringView3("verticalLayout")
	ui.verticalLayout.SetObjectName(*verticalLayout__objectName)
	verticalLayout__objectName.Delete() // setter copied value
	ui.verticalLayout.SetSpacing(0)
	ui.verticalLayout.SetContentsMargins(0, 0, 0, 0)
	ui.playerLayout = qt.NewQHBoxLayout2()
	playerLayout__objectName := qt.NewQAnyStringView3("playerLayout")
	ui.playerLayout.SetObjectName(*playerLayout__objectName)
	playerLayout__objectName.Delete() // setter copied value
	ui.playerLayout.SetContentsMargins(11, 11, 11, 11)
	ui.playerLayout.SetSpacing(6)
	ui.pauseButton = qt.NewQPushButton(ui.centralwidget)
	pauseButton__objectName := qt.NewQAnyStringView3("pauseButton")
	ui.pauseButton.SetObjectName(*pauseButton__objectName)
	pauseButton__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for pauseButton property 'minimumSize' */
	icon0 := qt.QIcon_FromTheme("media-playback-pause")
	ui.pauseButton.SetIcon(icon0)
	ui.pauseButton.SetFlat(true)

	ui.playerLayout.AddWidget(ui.pauseButton.QWidget)
	ui.stopButton = qt.NewQPushButton(ui.centralwidget)
	stopButton__objectName := qt.NewQAnyStringView3("stopButton")
	ui.stopButton.SetObjectName(*stopButton__objectName)
	stopButton__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for stopButton property 'minimumSize' */
	icon1 := qt.QIcon_FromTheme("media-playback-stop")
	ui.stopButton.SetIcon(icon1)
	ui.stopButton.SetFlat(true)

	ui.playerLayout.AddWidget(ui.stopButton.QWidget)
	ui.previousButton = qt.NewQPushButton(ui.centralwidget)
	previousButton__objectName := qt.NewQAnyStringView3("previousButton")
	ui.previousButton.SetObjectName(*previousButton__objectName)
	previousButton__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for previousButton property 'minimumSize' */
	icon2 := qt.QIcon_FromTheme("media-skip-backward")
	ui.previousButton.SetIcon(icon2)
	ui.previousButton.SetCheckable(false)
	ui.previousButton.SetFlat(true)

	ui.playerLayout.AddWidget(ui.previousButton.QWidget)
	ui.nextButton = qt.NewQPushButton(ui.centralwidget)
	nextButton__objectName := qt.NewQAnyStringView3("nextButton")
	ui.nextButton.SetObjectName(*nextButton__objectName)
	nextButton__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for nextButton property 'minimumSize' */
	icon3 := qt.QIcon_FromTheme("media-skip-forward")
	ui.nextButton.SetIcon(icon3)
	ui.nextButton.SetAutoDefault(false)
	ui.nextButton.SetDefault(false)
	ui.nextButton.SetFlat(true)

	ui.playerLayout.AddWidget(ui.nextButton.QWidget)
	ui.playerSlider = qt.NewQSlider(ui.centralwidget)
	playerSlider__objectName := qt.NewQAnyStringView3("playerSlider")
	ui.playerSlider.SetObjectName(*playerSlider__objectName)
	playerSlider__objectName.Delete() // setter copied value
	ui.playerSlider.SetOrientation(qt.Horizontal)

	ui.playerLayout.AddWidget(ui.playerSlider.QWidget)

	ui.verticalLayout.AddLayout(ui.playerLayout.QLayout)
	ui.RadioList = qt.NewQTableView(ui.centralwidget)
	RadioList__objectName := qt.NewQAnyStringView3("RadioList")
	ui.RadioList.SetObjectName(*RadioList__objectName)
	RadioList__objectName.Delete() // setter copied value

	ui.verticalLayout.AddWidget(ui.RadioList.QWidget)
	ui.MainWindow.SetCentralWidget(ui.centralwidget) // Set central widget
	ui.menubar = qt.NewQMenuBar(ui.MainWindow.QWidget)
	menubar__objectName := qt.NewQAnyStringView3("menubar")
	ui.menubar.SetObjectName(*menubar__objectName)
	menubar__objectName.Delete() // setter copied value
	ui.menubar.Resize(815, 23)
	ui.MainWindow.SetMenuBar(ui.menubar)
	ui.statusbar = qt.NewQStatusBar(ui.MainWindow.QWidget)
	statusbar__objectName := qt.NewQAnyStringView3("statusbar")
	ui.statusbar.SetObjectName(*statusbar__objectName)
	statusbar__objectName.Delete() // setter copied value
	ui.MainWindow.SetStatusBar(ui.statusbar)

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *MainWindowUi) Retranslate() {
	ui.MainWindow.SetWindowTitle(qt.QCoreApplication_Tr("qmRadio"))
	ui.pauseButton.SetText(qt.QWidget_Tr(""))
	ui.stopButton.SetText(qt.QWidget_Tr(""))
	ui.previousButton.SetText(qt.QWidget_Tr(""))
	ui.nextButton.SetText(qt.QWidget_Tr(""))
}
